- hosts: all
  name: Autoconverted job legacy-quibble-composer-sqlite-php72-docker from old job
    quibble-composer-sqlite-php72-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
