- hosts: all
  name: Autoconverted job legacy-mw-tools-codesniffer-mwcore-testrun from old job
    mw-tools-codesniffer-mwcore-testrun
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
