- hosts: all
  name: Autoconverted job legacy-pywikibot-core-tox-docker from old job pywikibot-core-tox-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
