- hosts: all
  name: Autoconverted job legacy-mwext-node10-rundoc-docker from old job mwext-node10-rundoc-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
