- hosts: all
  name: Autoconverted job legacy-integration-config-tox-docker from old job integration-config-tox-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
