- hosts: all
  name: Autoconverted job legacy-docker-pkg-tox-publish from old job docker-pkg-tox-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
