- hosts: all
  name: Autoconverted job legacy-mwnode10-docker from old job mwgate-node10-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
