FROM {{ "java8" | image_tag }}

COPY KEYS /tmp/KEYS
RUN {{ "gnupg wget" | apt_install }} \
    && cd /tmp \
    && wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227.zip \
    && wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227.zip.asc \
    && gpg --batch --import /tmp/KEYS \
    && gpg --verify sonar-scanner-cli-3.2.0.1227.zip.asc \
    && unzip -d sonar-scanner-cli-3.2.0.1227.zip \
    && apt purge --yes gnupg wget \
    && rm -rf ~/.gnupg

RUN /opt/sonar-scanner-3.2.0.1227/bin/sonar-scanner --version

USER nobody
WORKDIR /src
ENTRYPOINT ["/opt/sonar-scanner-3.2.0.1227/bin/sonar-scanner"]
