- hosts: all
  name: Autoconverted job legacy-wikiba.se-composer-php56-docker from old job wikiba.se-composer-php56-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
