- hosts: all
  name: Autoconverted job legacy-mediawiki-vagrant-rake-docker from old job mediawiki-vagrant-rake-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
