# MediaWiki Train automation
#
# Meant to automate all the steps of the weekly train as outlined on:
# <https://wikitech.wikimedia.org/wiki/Heterogeneous_deployment/Train_deploys>

# Update Deploy Notes
# <https://wikitech.wikimedia.org/wiki/Heterogeneous_deployment/Train_deploys#Update_deploy_notes>
- job:
    name: 'train-deploy-notes'
    node: train
    concurrent: false
    triggers:
      - zuul
    builders:
      - shell: |
          #!/usr/bin/env bash
          set -euxo pipefail

          if [[ "$ZUUL_OLDREV" != "0000000000000000000000000000000000000000" ]]; then
            echo "Job is only for new refs, not ref updates..."
            exit 1
          fi

          if [[ ! $ZUUL_REF =~ "refs/heads/wmf/1." ]]; then
            echo "Job is not for this branch..."
            exit 1
          fi
      - docker-log-dir
      - docker-src-dir
      - docker-run-with-log-cache-src:
          image: 'docker-registry.wikimedia.org/releng/release-notes:0.0.3'
          logdir: '/log'
    wrappers:
      - timeout:
          timeout: 30
      - timestamps
      - ansicolor
      - credentials-binding:
        - username-password-separated:
            credential-id: ReleaseNotesBot
            username: MEDIAWIKI_USR
            password: MEDIAWIKI_PSW
    publishers:
      - archive-log-dir
      - docker-cleanup
