- hosts: all
  name: Autoconverted job legacy-operations-mw-config-php72-composer-lint-docker from
    old job operations-mw-config-php72-composer-lint-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
