- hosts: all
  name: Autoconverted job legacy-labs-tools-ipwatcher-tox-docker from old job labs-tools-ipwatcher-tox-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
