- hosts: all
  name: Autoconverted job legacy-wikidata-query-gui-build from old job wikidata-query-gui-build
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          GIT_AUTHOR_NAME=WDQSGuiBuilder
          GIT_COMMITTER_NAME=WDQSGuiBuilder
          GIT_AUTHOR_EMAIL=wdqs-gui-build@lists.wikimedia.org
          GIT_COMMITTER_EMAIL=wdqs-gui-build@lists.wikimedia.org

          # We do not know Gerrit SSH host fingerprint
          mkdir -p ~/.ssh
          echo -ne 'Host gerrit.wikimedia.org\n  StrictHostKeyChecking no\nUser wdqsguibuilder\n' >> ~/.ssh/config

          npm run deploy
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
