- hosts: all
  name: Autoconverted job legacy-parsoidsvc-npm-run-roundtrip-node-6-docker from old
    job parsoidsvc-npm-run-roundtrip-node-6-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
