- hosts: all
  name: Autoconverted job legacy-mediawiki-core-jsduck-docker from old job mediawiki-core-jsduck-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
