- hosts: all
  name: Autoconverted job legacy-fresnel-node10-browser-docker from old job fresnel-node10-browser-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
