FROM {{ "java8" | image_tag }}

RUN {{ "phantomjs" | apt_install }}

# wikidata/query/rdf relies on npm
# See <https://docs.npmjs.com/misc/config#environment-variables>
# and <https://docs.npmjs.com/cli/cache>
ENV NPM_CONFIG_CACHE=/cache

