- hosts: all
  name: Autoconverted job legacy-mediawiki-fresnel-patch-docker from old job mediawiki-fresnel-patch-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -eux
          mkdir -m 2777 -p "log"
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -eux
          exec docker run --user=nobody --volume "$WORKSPACE":/workspace --entrypoint=/usr/bin/find \
            --init \
            --rm \
            --label "jenkins.job=$JOB_NAME" \
            --label "jenkins.build=$BUILD_NUMBER" \
            --env-file <(/usr/bin/env|egrep -v '^(HOME|SHELL|PATH|LOGNAME|MAIL|HHVM_REPO_CENTRAL_PATH)=') \
            'docker-registry.wikimedia.org/wikimedia-stretch:latest' "/workspace/log" -mindepth 1 -delete
          # nothing else can be executed due to exec
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -eux
          exec docker run --volume /srv/git:/srv/git:ro --tmpfs /workspace/db:size=320M --volume "$(pwd)"/log:/workspace/log \
            --init \
            --rm \
            --label "jenkins.job=$JOB_NAME" \
            --label "jenkins.build=$BUILD_NUMBER" \
            --env-file <(/usr/bin/env|egrep -v '^(HOME|SHELL|PATH|LOGNAME|MAIL|HHVM_REPO_CENTRAL_PATH)=') \
            'docker-registry.wikimedia.org/releng/quibble-fresnel:0.0.31-6' --packages-source vendor --db mysql --db-dir /workspace/db --skip-deps --commands "mediawiki-fresnel-patch"
          # nothing else can be executed due to exec
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
