- hosts: all
  name: Autoconverted job legacy-mediawiki-fresnel-patch-docker from old job mediawiki-fresnel-patch-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
