# Image to run analytics/refinery jars updater (T210271)
FROM {{ "ci-buster" | image_tag }}

USER root

# Dependencies for analytics/refinery bin/update-refinery-source-jars
RUN echo "deb http://apt.wikimedia.org/wikimedia buster-wikimedia main" > /etc/apt/sources.list.d/wikimedia.list
RUN {{ "git-fat curl wget" | apt_install }}
COPY run.sh /run.sh

USER nobody

WORKDIR /src

ENTRYPOINT ["/run.sh"]
