FROM {{ "ci-jessie" | image_tag }}

RUN git clone --depth 1 https://gerrit.wikimedia.org/r/p/integration/jenkins.git /srv/jenkins && \
    rm -rf /srv/jenkins/.git

FROM {{ "ci-jessie" | image_tag }}

RUN cp /srv/jenkins/bin /srv/slave-scripts
RUN cp /srv/jenkins/etc/zuul-clonemap.yaml /srv/zuul-clonemap.yaml

USER nobody
