#!/bin/bash
# vim: set et ts=4 sw=4:

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# 'jenkins' user is added by devuser/install.d/50-devuser

DIB_WIKIMEDIA_PUPPET_DEST=${DIB_WIKIMEDIA_PUPPET_DEST:-/puppet}

mkdir -v -p $(dirname $DIB_WIKIMEDIA_PUPPET_DEST)
echo "Cloning puppet.git from instance bare mirror"
git clone /srv/git/operations/puppet.git "$DIB_WIKIMEDIA_PUPPET_DEST"

echo "Changing remote from instance mirror to Gerrit..."
git -C "$DIB_WIKIMEDIA_PUPPET_DEST" remote -v
git -C "$DIB_WIKIMEDIA_PUPPET_DEST" remote set-url origin https://gerrit.wikimedia.org/r/p/operations/puppet
git -C "$DIB_WIKIMEDIA_PUPPET_DEST" remote -v

echo "Asserting puppet is installed..."
which puppet

echo "Preparing puppet links..."
for dir in files hieradata manifests modules templates; do
    rm -f -R -v "/etc/puppet/$dir"
    ln -v -s $DIB_WIKIMEDIA_PUPPET_DEST/$dir  /etc/puppet/$dir
done;

echo "Applying puppet manifests ..."
puppet-apply /tmp/in_target.d/wikimedia-puppet/bootstrap.pp
puppet-apply /tmp/in_target.d/wikimedia-puppet/aptconf.pp
apt-get -q update
puppet-apply /tmp/in_target.d/wikimedia-puppet/ciimage.pp

echo "Performing apt-get dist-upgrade"
# Hack to allow downgrading T133528
APT_CONFIG=`mktemp`
echo 'APT::Get::force-yes "true";' > $APT_CONFIG
APT_CONFIG=$APT_CONFIG install-packages -u
rm $APT_CONFIG
