FROM {{ "php-ast" | image_tag }} as ast

FROM {{ "composer-package-php70" | image_tag }} as composer-package

FROM {{ "composer-php80" | image_tag }}

USER root

# This will override the already-existing ast
COPY --from=ast /usr/lib/php/20200930/ast.so /usr/lib/php/20200930/ast.so
COPY --from=ast /srv/20-ast.ini /etc/php/8.0/cli/conf.d/20-ast.ini

USER nobody
COPY --from=composer-package /run.sh /run.sh
ENTRYPOINT ["/run.sh"]
