- hosts: all
  name: Autoconverted job legacy-recommendation-api-deploy-npm-node-6-docker from
    old job recommendation-api-deploy-npm-node-6-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
