- hosts: all
  name: Autoconverted job legacy-mwext-phpunit-coverage-patch-docker from old job
    mwext-phpunit-coverage-patch-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
