- hosts: all
  name: Autoconverted job legacy-integration-config-zuul-layout-diff-docker from old
    job integration-config-zuul-layout-diff-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
