- hosts: all
  name: Autoconverted job legacy-labs-striker-tox-docker from old job labs-striker-tox-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
