- hosts: all
  name: Autoconverted job legacy-doxygen-publish from old job doxygen-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
