- hosts: all
  name: Autoconverted job legacy-quibble-donationinterface-REL1_31-php70-docker from
    old job quibble-donationinterface-REL1_31-php70-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
