- hosts: all
  name: Autoconverted job legacy-composer-package-php70-docker from old job composer-package-php70-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
