FROM {{ "ci-buster" | image_tag }}

USER root

# php-cli is for filters
# Doxygen got backported
RUN echo "deb http://apt.wikimedia.org/wikimedia buster-wikimedia component/ci" > /etc/apt/sources.list.d/component-ci.list \
    && {{ "doxygen graphviz php-cli" | apt_install }}

COPY run.sh /run.sh

USER nobody
ENTRYPOINT ["/run.sh"]
