- hosts: all
  name: Autoconverted job legacy-translatewiki-composer-hhvm-docker from old job translatewiki-composer-hhvm-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
