- hosts: all
  name: Autoconverted job legacy-jenkins-plugin-postbuildscript-maven-java8-docker
    from old job jenkins-plugin-postbuildscript-maven-java8-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
