- hosts: all
  name: Autoconverted job legacy-operations-puppet-tests-stretch-docker from old job
    operations-puppet-tests-stretch-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -eux
          mkdir -m 2777 -p "log"
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -eux
          exec docker run --user=nobody --volume "$WORKSPACE":/workspace --entrypoint=/usr/bin/find \
            --init \
            --rm \
            --label "jenkins.job=$JOB_NAME" \
            --label "jenkins.build=$BUILD_NUMBER" \
            --env-file <(/usr/bin/env|egrep -v '^(HOME|SHELL|PATH|LOGNAME|MAIL|HHVM_REPO_CENTRAL_PATH)=') \
            'docker-registry.wikimedia.org/wikimedia-stretch:latest' "/workspace/log" -mindepth 1 -delete
          # nothing else can be executed due to exec
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: "set -eux\nexec docker run  --volume \"$(pwd)\"/log:/srv/workspace/log\
          \ \\\n  --init \\\n  --rm \\\n  --label \"jenkins.job=$JOB_NAME\" \\\n \
          \ --label \"jenkins.build=$BUILD_NUMBER\" \\\n  --env-file <(/usr/bin/env|egrep\
          \ -v '^(HOME|SHELL|PATH|LOGNAME|MAIL|HHVM_REPO_CENTRAL_PATH)=') \\\n  'docker-registry.wikimedia.org/releng/operations-puppet:0.5.2'\
          \ \n# nothing else can be executed due to exec\n"
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
