- hosts: all
  name: Autoconverted job legacy-wikimedia-fundraising-crm-composer-php56-docker from
    old job wikimedia-fundraising-crm-composer-php56-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
