- hosts: all
  name: Autoconverted job legacy-oojs-ui-npm-run-jenkins-node-6-docker from old job
    oojs-ui-npm-run-jenkins-node-6-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
