- hosts: all
  name: Autoconverted job legacy-labs-tools-wikibugs2-autopull from old job labs-tools-wikibugs2-autopull
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
