- hosts: all
  name: Autoconverted job legacy-mwcomposer-hhvm-docker from old job mwgate-composer-hhvm-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
