- hosts: all
  name: Autoconverted job legacy-analytics-wikistats2-npm-browser-node-6-docker from
    old job analytics-wikistats2-npm-browser-node-6-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
