- hosts: all
  name: Autoconverted job legacy-mediawiki-i18n-check-docker from old job mediawiki-i18n-check-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -uxo pipefail
          cd src

          # Assumption: Any messages containing literal js will end in .js. Any other
          # raw html message is in normal html context (not attribute)

          git show FETCH_HEAD -U0 | grep '^+' | sed -E -e 's/<\/? ?(abbr|span|br|strong|em|pre|nowiki|charinsert|b|del|code|kbd|p|tt|div|i|big|sup|sub|samp|var|small|h1|h2|h3|h4|u)( ((class|title|lang|xml:lang|dir)=\\?["'\''][^=<>"'\'']*\\?["'\'']))* ?\/?>//g' -e 's/<!--//g' -e 's/<https?:\/\/[a-zA-Z0-9./-]*>//g' | grep '<'
          if [[ $? == 0 ]]; then
            echo "HTML detected. Manual review required"
            exit 1
          else
            echo 'ok'
          fi

          git show FETCH_HEAD -U0 | grep '^+' | sed -E -e 's/\\\\//g' -e 's/\\[nt"]//g' | grep '\\'
          if [[ $? == 0 ]]; then
            echo "JSON escape sequence detected. Manual review required"
            exit 1
          else
            echo 'ok'
          fi

          exit 0
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
