FROM {{ "quibble-stretch" | image_tag }}

USER root

# Wikibase and WikibaseLexeme use Firefox
RUN {{ "firefox-esr" | apt_install }}
COPY firefox /usr/local/bin/firefox

RUN {{ "libav-tools build-essential rubygems-integration ruby ruby-dev bundler" | apt_install }}

COPY mwselenium.sh /usr/local/bin/mwselenium

# Unprivileged
USER nobody
WORKDIR /workspace
ENTRYPOINT ["/usr/local/bin/quibble", "--commands", "mwselenium"]
