- hosts: all
  name: Autoconverted job legacy-mediawiki-ruby-api-rake-docker from old job mediawiki-ruby-api-rake-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
