FROM {{ "php-ast" | image_tag }} as ast

FROM {{ "composer-package-php70" | image_tag }} as composer-package

FROM {{ "composer-php73" | image_tag }}

USER root

# This will override the already-existing ast
COPY --from=ast /usr/lib/php/20180731/ast.so /usr/lib/php/20180731/ast.so

USER nobody
COPY --from=composer-package /run.sh /run.sh
ENTRYPOINT ["/run.sh"]
