- hosts: all
  name: Autoconverted job legacy-wikibase-repo-docker from old job wikibase-repo-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
