#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Puppet exit codes are handled manually
set +e
puppet apply --test --verbose --modulepath=/srv/git/operations/puppet/modules /srv/git/operations/puppet/modules/contint/manifests/packages/python.pp

EXIT_CODE=$?
if [[ "$EXIT_CODE" == "4" || "$EXIT_CODE" == "6" ]]; then
	>&2 echo "Puppet run failed with exit code $EXIT_CODE"
	exit $EXIT_CODE
fi;
set -e
