- hosts: all
  name: Autoconverted job legacy-chromium-render-npm-browser-node-6-docker from old
    job chromium-render-npm-browser-node-6-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
