- hosts: all
  name: Autoconverted job legacy-mwext-npm-doc-publish from old job mwext-npm-doc-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
