- hosts: all
  name: Autoconverted job legacy-php-compile-php71-docker from old job php-compile-php71-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
