- hosts: all
  name: Autoconverted job legacy-phpunit-coverage-docker-publish from old job phpunit-coverage-docker-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
