#!/bin/bash -e
#
# Usage: ./debug-image node10-test
#
# Trailing slash is optional, such as when autocompleting names in
# your shell from within the dockerfiles/ directory.

name=$1
if [ -z "$name" ]; then
	echo "Please provide an image name!"
	exit 1
fi
name=$(basename $name)

version=$2
version=${version:-"latest"}

prefix=docker-registry.wikimedia.org/releng
image=$prefix/$name:$version

exec docker run --rm --tty --interactive \
	 --entrypoint /bin/bash $image
