#!/bin/bash -eu
#
# Usage: ./debug-image node10-test
#
# Trailing slash is optional, such as when autocompleting names
# in your shell from within the dockerfiles/ directory.

image=$(basename "$1")

exec docker run \
    --rm --tty \
    --interactive --entrypoint /bin/bash \
    docker-registry.wikimedia.org/releng/"$image":latest
