- hosts: all
  name: Autoconverted job legacy-search-mjolnir-tox-docker from old job search-mjolnir-tox-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
