- hosts: all
  name: Autoconverted job legacy-mwskin-php70-phan-docker from old job mwskin-php70-phan-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
