- hosts: all
  name: Autoconverted job legacy-pywikibot-CommonsDelinker-tox-docker from old job
    pywikibot-CommonsDelinker-tox-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
