FROM {{ "ci-jessie" | image_tag }}

# DO NOT CHANGE VERSION WITHOUT INVOLVING Krinkle OR hashar
ARG NPM_VERSION="3.8.3"

# Install nodejs-legacy to provide /usr/bin/node alias
RUN {{ "nodejs-legacy npm" | apt_install }} \
    && npm install -g npm@${NPM_VERSION}

USER nobody

ENTRYPOINT ["npm"]
CMD ["--help"]
