- hosts: all
  name: Autoconverted job legacy-labs-tools-map-of-monuments-tox-docker from old job
    labs-tools-map-of-monuments-tox-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
