- hosts: all
  name: Autoconverted job legacy-parsoidsvc-composer-package-php73-docker from old
    job parsoidsvc-composer-package-php73-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
