FROM {{ "npm-test" | image_tag }}

USER root

{% set deps|replace('\n', ' ') -%}
libcairo2-dev
libgif-dev
libpango1.0-dev
libjpeg62-turbo-dev
fonts-dejavu
libboost-filesystem-dev
libboost-program-options-dev
libboost-regex-dev
libboost-system-dev
libboost-thread-dev
libgdal-dev
libicu-dev
libpq-dev
libcurl4-gnutls-dev
libproj-dev
libtiff-dev
libwebp5
libmapbox-variant-dev
libmapnik-dev
mapnik-utils
librdkafka-dev/jessie-wikimedia
{%- endset -%}

RUN {{ deps | apt_install }}

USER nobody
