- hosts: all
  name: Autoconverted job legacy-wikidata-query-rdf-maven-java8-docker from old job
    wikidata-query-rdf-maven-java8-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
