FROM {{ "composer" | image_tag }}

USER nobody

# Warm up composer cache
RUN mkdir -p /tmp/composer && \
    cd /tmp/composer && \
    composer require --dev mediawiki/phan-taint-check-plugin 1.1.0 && \
    cd / && \
    rm -rf /tmp/composer

COPY run.sh /run.sh
ENTRYPOINT ["/run.sh"]
