- hosts: all
  name: Autoconverted job legacy-gerrit-plugins-barricade-maven-java8-docker from
    old job gerrit-plugins-barricade-maven-java8-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
