- hosts: all
  name: Autoconverted job legacy-ooui-npm-special-node10-plus-composer-docker from
    old job ooui-npm-special-node10-plus-composer-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
