- hosts: all
  name: Autoconverted job legacy-mw-tools-releng-tox-publish from old job mw-tools-releng-tox-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
