- hosts: all
  name: Autoconverted job legacy-wikipeg-npm-php-docker from old job wikipeg-npm-php-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
