- hosts: all
  name: Autoconverted job legacy-trigger-blubber-pipeline-test from old job trigger-blubber-pipeline-test
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
