- hosts: all
  name: Autoconverted job legacy-mwext-node10-docs-docker-publish from old job mwext-node10-docs-docker-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
