#!/bin/bash
# vim: set et ts=4 sw=4:

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

DIB_WIKIMEDIA_PUPPET_SOURCE=${DIB_WIKIMEDIA_PUPPET_SOURCE:-./puppet}

mkdir -p $TMP_HOOKS_PATH/wikimedia-puppet
cp -a -v $DIB_WIKIMEDIA_PUPPET_SOURCE/*.pp  $TMP_HOOKS_PATH/wikimedia-puppet
