- hosts: all
  name: Autoconverted job legacy-parsoidsvc-parsertests-docker from old job parsoidsvc-parsertests-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
