- hosts: all
  name: Autoconverted job legacy-mediawiki-selenium-integration-docker from old job
    mediawiki-selenium-integration-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
