- hosts: all
  name: Autoconverted job legacy-pywikibot-core-tox-fasttest-py27-docker from old
    job pywikibot-core-tox-fasttest-py27-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
