- hosts: all
  name: Autoconverted job legacy-wikidata-query-gui-npm-browser-node-6-docker from
    old job wikidata-query-gui-npm-browser-node-6-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
