- hosts: all
  name: Autoconverted job legacy-parsoidsvc-doxygen-publish from old job parsoidsvc-doxygen-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
