FROM {{ "php-ast" | image_tag }} as ast

FROM {{ "composer-package-php70" | image_tag }} as composer-package

FROM {{ "composer-php71" | image_tag }}

USER root

# FIXME: Don't hardcode the phpapi version (but php-config is in php-dev pkg)
# This will override the already-existing ast
COPY --from=ast /usr/lib/php/20160303/ast.so /usr/lib/php/20160303/ast.so

USER nobody
COPY --from=composer-package /run.sh /run.sh
ENTRYPOINT /bin/bash /run.sh
