- hosts: all
  name: Autoconverted job legacy-quibble-composer-mysql-php73-noselenium-docker from
    old job quibble-composer-mysql-php73-noselenium-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
