- hosts: all
  name: Autoconverted job legacy-discovery-maven-tool-configs-maven-java8-docker from
    old job discovery-maven-tool-configs-maven-java8-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
