FROM {{ "ci-buster" | image_tag }}

USER root

RUN {{ "make asciidoc source-highlight devscripts python3 python3-pip python3-yaml python3-autopep8 python3-git python3-jinja2" | apt_install }}

USER nobody
WORKDIR /src
ENTRYPOINT [ "/usr/bin/make" ]
