- hosts: all
  name: Autoconverted job legacy-oojs-router-node10-browser-docker from old job oojs-router-node10-browser-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
