- hosts: all
  name: Autoconverted job legacy-search-glent-maven-java8-docker-site-publish from
    old job search-glent-maven-java8-docker-site-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
