- hosts: all
  name: Autoconverted job legacy-mediawiki-quibble-composertest-php70-docker from
    old job mediawiki-quibble-composertest-php70-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
