- hosts: all
  name: Autoconverted job legacy-visualeditor-rake-docker from old job visualeditor-rake-docker
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
