FROM {{ 'npm' | image_tag }}

USER root

USER nobody
COPY run.sh /run.sh
COPY run-oid.sh /run-oid.sh
# Add a script that is able to install solely the devDependencies
COPY npm-install-dev.py /npm-install-dev.py
ENTRYPOINT ["/run.sh"]
