- hosts: all
  name: Autoconverted job legacy-integration-pipelinelib-docker-doc-publish from old
    job integration-pipelinelib-docker-doc-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
