# Docker image with nodejs, jsduck, and browsers installed.
# Executes 'npm run {cmd:test}' in /src.

FROM {{ "node10-test" | image_tag }}

USER root

# browsers for tools that use headless chrome, and for selenium tests
RUN {{ "chromium chromium-driver firefox-esr" | apt_install }}
COPY firefox /usr/local/bin/firefox

USER nobody

# For karma-chrome-launcher
ENV CHROME_BIN=/usr/bin/chromium

# For karma-firefox-launcher
ENV FIREFOX_BIN=/usr/local/bin/firefox
