- hosts: all
  name: Autoconverted job legacy-mediawiki-selenium-bundle-yard-publish from old job
    mediawiki-selenium-bundle-yard-publish
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory
