FROM wmfreleng/composer:latest as composer

FROM {{ "php55" | image_tag }}

COPY --from=composer /srv/composer /srv/composer
COPY --from=composer /.cache-buster-composer /.cache-buster-composer
# Manually link since COPY copies symlink destination instead of the actual symlink
USER root
RUN ln -s /srv/composer/vendor/bin/composer /usr/bin/composer

USER nobody

ENTRYPOINT ["/srv/composer/vendor/bin/composer"]
CMD ["help"]
